apiVersion: batch/v1
kind: Job
metadata:
  name: trace_kd-job
spec:
  template:
    spec:
      containers:
      - name: trace_kd-container
        image: trace_kd:latest
        command: ["python", "scripts/testing.py"]
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "4"
            memory: "16Gi"
          limits:
            cpu: "8"
            memory: "32Gi"
        volumeMounts:
        - name: sf-storage
          mountPath: /app/data
      restartPolicy: Never
      volumes:
      - name: sf-storage
        persistentVolumeClaim:
          claimName: sf-pvc
  backoffLimit: 4
